# Generated by Django 5.1.3 on 2024-11-22 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customer_remove_room_room_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomhistory',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='roomhistory',
            name='room',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='RoomHistory',
        ),
    ]
